In [1]:
import numpy as np

In [2]:
a = np.arange(24).reshape(2, 3, 4) + 1

In [3]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [4]:
a.argmax(axis=0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
a.argmax(axis=1)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [6]:
a.argmax(axis=2)

array([[3, 3, 3],
       [3, 3, 3]])

# 总结
argmax官方简介是Returns the indices of the maximum values along an axis.
<br/>理解中的axis的作用：
<br/>
<br/>原张量(2, 3, 4)
<br/>一.
<br/>axis = 0
<br/>(2, 3, 4) -> (3, 4)
<br/>axis = 1
<br/>(2, 3, 4) -> (2, 4)
<br/>axis = 2
<br/>(2, 3, 4) -> (2, 3)
<br/>二.
<br/>axis = 0
<br/>沿着dim 0挨个比较元素(0, 0, 0)和(1, 0, 0)作为(3, 4)的(0, 0)位置的元素，最大index = 1(<2)
<br/>沿着dim 0挨个比较元素(0, 0, 1)和(1, 0, 1)作为(3, 4)的(0, 1)位置的元素
<br/>以此类推，沿着dim 0挨个比较元素 (0, 2, 3)和(1, 2, 3)比较作为(3, 4)的(2, 3)位置的元素
<br/>axis = 1
<br/>沿着dim 1挨个比较元素(0, 0, 0)，(0, 1, 0)和(0, 2, 0)作为(2, 4)的(0, 0)位置的元素
<br/>沿着dim 1挨个比较元素(0, 0, 1)，(0, 1, 1)和(0, 2, 1)作为(2, 4)的(0, 1)位置的元素
<br/>以此类推，沿着dim 1挨个比较元素(1, 0, 3)，(1, 1, 3)和(1, 2, 3)作为(2, 4)的(1, 3)位置的元素
<br/>axis = 2
<br/>沿着dim 2挨个比较元素(0, 0, 0)，(0, 0, 1)，(0, 0, 2)和(0, 0, 3)作为(2, 3)的(0, 0)位置的元素
<br/>沿着dim 2挨个比较元素(0, 1, 0)，(0, 1, 1)，(0, 1, 2)和(0, 1, 3)作为(2, 3)的(0, 1)位置的元素
<br/>以此类推，沿着dim 2挨个比较元素(0, 1, 0)，(0, 1, 1)，(0, 1, 2)和(0, 1, 3)作为(2, 3)的(0, 1)位置的元素