In [2]:
import numpy as np

In [88]:
a = np.array([
    [[1, 1, 1, 1], 
    [2, 2, 2, 2],
    [3, 3, 3, 3]],
    
    [[4, 4, 4, 4], 
    [5, 5, 5, 5],
    [6, 6, 6, 6]]
])

In [89]:
a.shape

(2, 3, 4)

In [90]:
a.mean(axis = 0)

array([[2.5, 2.5, 2.5, 2.5],
       [3.5, 3.5, 3.5, 3.5],
       [4.5, 4.5, 4.5, 4.5]])

In [91]:
a.mean(axis = 1)

array([[2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [96]:
a.mean(axis = (0, 2))

array([2.5, 3.5, 4.5])

In [93]:
a.mean(axis = (0, 1))

array([3.5, 3.5, 3.5, 3.5])

In [94]:
a.mean(axis = (1, 2))

array([2., 5.])

# 总结

## axis = 0 
结果为shape = (3, 4) 沿着0轴 
<br/>
(0, 0, 0), (1, 0, 0)作为(3, 4)位置(0, 0)的元素
<br/>
(0, 2, 3), (1, 2, 3)作为(3, 4)位置(2, 3)的元素
<br/>
## axis = (0, 2)
结果为shape = (3,) 沿着0轴和2轴 
<br/>
(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 0, 3)  (1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 0, 3)作为(3, )位置(0, )的元素
<br/>
(0, 2, 0), (0, 2, 1), (0, 2, 2), (0, 2, 3)  (1, 2, 0), (1, 2, 1), (1, 2, 2), (1, 2, 3)作为(3, )位置(2, )的元素
<br/>
## axis = (1, 2)
结果为shape = (2,) 沿着1轴和2轴 
<br/>
(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 0, 3)
<br/>
(0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 1, 3)
<br/>
(0, 2, 0), (0, 2, 1), (0, 2, 2), (0, 2, 3)
<br/>
作为(3, )位置(0, )的元素
<br/>
(1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 0, 3)
<br/>
(1, 1, 0), (1, 1, 1), (1, 1, 2), (1, 1, 3)
<br/>
(1, 2, 0), (1, 2, 1), (1, 2, 2), (1, 2, 3)
<br/>
作为(3, )位置(1, )的元素
<br/>