In [2]:
import torch
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [4]:
b = torch.tensor(a)

In [5]:
c = torch.as_tensor(a)

In [6]:
b.sub_(1)

tensor([0, 1, 2])

In [7]:
a

array([1, 2, 3])

In [8]:
c.sub_(1)

tensor([0, 1, 2])

In [9]:
a

array([0, 1, 2])