In [1]:
import torch

In [2]:
input = torch.ones(3,2,5,5)
h = torch.flatten(input, 1)
x = torch.nn.Linear(2*5*5, 4)
out = x(h)

In [3]:
out.shape, out

(torch.Size([3, 4]),
 tensor([[ 0.4781, -0.3531, -0.1763, -1.1143],
         [ 0.4781, -0.3531, -0.1763, -1.1143],
         [ 0.4781, -0.3531, -0.1763, -1.1143]], grad_fn=<AddmmBackward>))

In [4]:
input.shape, input

(torch.Size([3, 2, 5, 5]),
 tensor([[[[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],
 
          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]]],
 
 
         [[[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],
 
          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]]],
 
 
         [[[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],
 
          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 

In [5]:
h.shape, h

(torch.Size([3, 50]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]))

In [6]:
h.matmul(x.weight.t()) # 类似于1x50的矩阵乘以50x4的矩阵，最后结果为1x4的矩阵

tensor([[ 0.5372, -0.4439, -0.1408, -1.0315],
        [ 0.5372, -0.4439, -0.1408, -1.0315],
        [ 0.5372, -0.4439, -0.1408, -1.0315]], grad_fn=<MmBackward>)

In [7]:
h.matmul(x.weight.t())+x.bias

tensor([[ 0.4781, -0.3531, -0.1763, -1.1143],
        [ 0.4781, -0.3531, -0.1763, -1.1143],
        [ 0.4781, -0.3531, -0.1763, -1.1143]], grad_fn=<AddBackward0>)

In [8]:
x.weight.t().shape

torch.Size([50, 4])

In [9]:
x.weight.t().sum(dim=0)

tensor([ 0.5372, -0.4439, -0.1408, -1.0315], grad_fn=<SumBackward1>)