In [1]:
import torch

In [2]:
x = torch.tensor([[1, 2], [4, 3]])

In [3]:
x.max(1)

torch.return_types.max(
values=tensor([2, 4]),
indices=tensor([1, 0]))

In [4]:
_, preds = x.max(1)

In [5]:
preds

tensor([1, 0])

In [6]:
preds.item()

ValueError: only one element tensors can be converted to Python scalars

In [7]:
_, preds = x.max(1, keepdim=True)

In [8]:
preds

tensor([[1],
        [0]])

In [9]:
preds[0]

tensor([1])

In [10]:
preds[0].item()

1

In [11]:
x = torch.tensor([[[1, 2], [4, 3]], [[2, 1], [3, 4]]])

In [12]:
x

tensor([[[1, 2],
         [4, 3]],

        [[2, 1],
         [3, 4]]])

In [13]:
x.shape

torch.Size([2, 2, 2])

In [14]:
x.max(1)

torch.return_types.max(
values=tensor([[4, 3],
        [3, 4]]),
indices=tensor([[1, 1],
        [1, 1]]))

In [15]:
x.max(1)[1].shape

torch.Size([2, 2])

In [16]:
d = x.max(1, keepdim=True)

In [17]:
d

torch.return_types.max(
values=tensor([[[4, 3]],

        [[3, 4]]]),
indices=tensor([[[1, 1]],

        [[1, 1]]]))

In [18]:
d[1].shape

torch.Size([2, 1, 2])

In [19]:
d[1][0]

tensor([[1, 1]])

In [21]:
d[1][0].item()

ValueError: only one element tensors can be converted to Python scalars