In [1]:
import torch

In [38]:
input = torch.ones(3,2,5,5)
h = torch.flatten(input, 1)
x = torch.nn.Linear(2*5*5, 4)
out = x(h)

In [39]:
out.shape, out

(torch.Size([3, 4]),
 tensor([[-0.3482,  0.0343, -0.0182, -0.1421],
         [-0.3482,  0.0343, -0.0182, -0.1421],
         [-0.3482,  0.0343, -0.0182, -0.1421]], grad_fn=<AddmmBackward>))

In [40]:
input.shape, input

(torch.Size([3, 2, 5, 5]),
 tensor([[[[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],
 
          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]]],
 
 
         [[[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],
 
          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]]],
 
 
         [[[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],
 
          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 

In [41]:
h.shape, h

(torch.Size([3, 50]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]))

In [42]:
h.matmul(x.weight.t())

tensor([[-0.4551, -0.1033,  0.0727, -0.1567],
        [-0.4551, -0.1033,  0.0727, -0.1567],
        [-0.4551, -0.1033,  0.0727, -0.1567]], grad_fn=<MmBackward>)

In [43]:
x.weight.t().shape, x.weight.t() # t表示转置

(torch.Size([50, 4]),
 tensor([[-0.1256, -0.0866, -0.1174, -0.0102],
         [-0.0230,  0.0526, -0.0177, -0.1086],
         [-0.0964,  0.1169, -0.0158,  0.0576],
         [-0.1205, -0.1177,  0.1037, -0.0484],
         [ 0.0512,  0.0292,  0.0155,  0.0461],
         [-0.0739,  0.1199,  0.0988,  0.1100],
         [ 0.0475, -0.0863, -0.0914, -0.0726],
         [ 0.0848, -0.0570,  0.1102,  0.0138],
         [ 0.1322, -0.0639,  0.1260, -0.0650],
         [-0.0862,  0.0773, -0.0864, -0.0359],
         [-0.0924,  0.0722, -0.1071, -0.0732],
         [-0.0701, -0.0113, -0.1203,  0.0495],
         [-0.0486,  0.1269, -0.0441, -0.0876],
         [-0.0649, -0.0757, -0.1099, -0.1134],
         [-0.1307, -0.0329,  0.0114,  0.0768],
         [ 0.0197, -0.0605,  0.1273, -0.0071],
         [ 0.0277,  0.0423, -0.0932,  0.0501],
         [ 0.1145,  0.0666,  0.0473,  0.1321],
         [-0.0879, -0.0706, -0.0672,  0.0273],
         [-0.1141, -0.1109,  0.0918,  0.0694],
         [-0.0830,  0.1310,  0.0860, -

In [44]:
x.weight.sum(dim=1)

tensor([-0.4551, -0.1033,  0.0727, -0.1567], grad_fn=<SumBackward1>)

In [37]:
x.weight

Parameter containing:
tensor([[ 0.0499,  0.0179,  0.0174, -0.0248, -0.0220, -0.0192, -0.0216, -0.0013,
          0.0986,  0.0112,  0.0165,  0.0478,  0.0626, -0.0071,  0.0931,  0.1124,
         -0.1108, -0.0939,  0.0087,  0.1032, -0.0692,  0.0169, -0.0999,  0.0186,
          0.0493, -0.0159,  0.0962,  0.0917, -0.0616,  0.1148, -0.0341,  0.0116,
         -0.0824, -0.1092, -0.0976, -0.0780,  0.0925,  0.0516,  0.0719,  0.0201,
         -0.0657, -0.0760, -0.0660, -0.0532, -0.0380, -0.0024,  0.0763,  0.0978,
          0.1140, -0.0766,  0.0621, -0.1004,  0.1152, -0.0393, -0.0365, -0.1099,
         -0.0338, -0.1041,  0.0412, -0.0130, -0.0395, -0.0971, -0.0177,  0.0314,
          0.0059,  0.0430,  0.0865,  0.0458, -0.0085,  0.0610,  0.0599, -0.0860,
         -0.0709,  0.0966,  0.0396],
        [-0.1069, -0.0008,  0.0272,  0.0332, -0.0018,  0.0514, -0.0685, -0.0719,
         -0.0879, -0.0370, -0.0073, -0.0588,  0.0158, -0.0765,  0.0086, -0.0012,
         -0.0003, -0.0104, -0.1040, -0.0347,  0.08